### ISSUE TITLE
ESPHome functionality

### ISSUE THREAD

**Issue by JoeAverge9** [thelastoutpostworkshop/gpio_viewer#50]
Would it be possible to enable this within the ESPHome project?
https://www.esphome.io/

**Comment by JoeAverge9** [comment]
I also found a similar request going the same way. Not sure where the best place for this request should be.
https://github.com/esphome/feature-requests/issues/2546

**Comment by thelastoutpostworkshop** [comment]
I don't know ESPHome.  Are you creating a sketch when working with ESPHome ?

**Comment by JoeAverge9** [comment]
> I don't know ESPHome. Are you creating a sketch when working with ESPHome ?

ESPHome is a declarative framework for programing ESP32 and ESP8266 dev boards

**Comment by thelastoutpostworkshop** [comment]
Can you import libraries ?

**Comment by JoeAverge9** [comment]
> Can you import libraries ?

I do not know for sure but depending on what you declare in the YAML config I believe this happens during the compile process before upload.

**Comment by thelastoutpostworkshop** [comment]
I will have a look at their documentation, if they don't allow third party libraries, there is not much I will able to do

**Comment by trantoriana** [comment]
ESPHome does  allow importing external components using the 'external' component:

* https://esphome.io/components/external_components.html

@thelastoutpostworkshop  : Would be great if I knew what to import.

I am willing to test this and contribute to documenting.

T.

**Comment by thelastoutpostworkshop** [comment]
Thanks a lot for the info and sure I will need help for testing.

**Comment by trantoriana** [comment]
It looks like the source needs to be rearrange in a specific format to allow ESPHome to import such a 'component', as per:

* https://esphome.io/guides/contributing#contributing-to-esphome

Perhaps core developers of ESPHome are willing to contribute turning GPIOViewer into such a component.

Fingers crossed

**Comment by thelastoutpostworkshop** [comment]
Yes and some people open issues on it, on the ESPHome repository

**Comment by thelastoutpostworkshop** [comment]
It appears, that IDF is needed for ESPHome, currently GPIOViewer library is based on the Arduino Framework.  So a port to IDF is needed, I do not know at this point the amount of work this port will required.

**Comment by trantoriana** [comment]
If i'd only knew what this means, but it seems possible to create a arduino based library as component in IDF.

At least, that is what it looks like they done here:

* https://github.com/sukesh-ak/Arduino-Library-with-IDF

Perhaps a similar method can be used here ??

**Comment by thelastoutpostworkshop** [comment]
Thanks I will look into it

**Comment by oka4henry** [comment]
> Can you import libraries ?

Yes

**Comment by oka4henry** [comment]
Yes, you can.

**Comment by platte-73** [comment]
So, is it possible to use GPIO Viewer with ESPHome?

**Comment by thelastoutpostworkshop** [comment]
I think so, if someone wants to submit PRs for it, you are welcomed.

**Comment by tache** [comment]
First, this is an awesome capability.
Second, I am +1 for the functionality being on ESPHome. Has anyone started the effort yet? I am on board to help.

**Comment by thelastoutpostworkshop** [comment]
Nobody submitted PRs for this yet, your are welcome to contribute.

**Comment by tache** [comment]
Going to give it a go, but got to get up to speed on ESPHome component development and then off to the races.

**Comment by thelastoutpostworkshop** [comment]
Thanks, I do not know how much of a learning curve it is.

**Comment by erazor666** [comment]
I really like this functionality and I really hope someone makes it come to pass. Not much good on coding mysel sadly 🤔

**Comment by mikulik86** [comment]
+1

**Comment by AJ-Github-Account** [comment]
+1

**Comment by Joo01** [comment]
Yes, GPIOViewer in ESPHome would be a perfect addition!
Hope someone gets it working :-)

**Comment by Jaharmi** [comment]
This looks great, just found it and am also interested in the possibility with ESPHome. In the meantime, for a particular problem I’m having, I was thinking I’d temporarily re-flash the affected device. It’s not like the config for that device will go away in ESPHome.

**Comment by Jaharmi** [comment]
I was able to add this to ESPHome.

```
esphome:
  libraries:
    # A library from PlatformIO
    - thelastoutpostworkshop/GPIOViewer
```

However, I don’t think this results in the “#include” being set and the Web server running on port 8080. I may be wrong, as the ESPHome device I was testing already had a Web server on port 80. (This also meant it had the other required libraries installed.)

**Comment by MrC0nst** [comment]
> I was able to add this to ESPHome.
> 
> ```
> esphome:
>   libraries:
>     # A library from PlatformIO
>     - thelastoutpostworkshop/GPIOViewer
> ```

So you have this addon working in esphome just with 4 lines of code only?
I cant reach 80 or 8080 port of my esp to view gpio states

**Comment by MrC0nst** [comment]
This example works only with inpit pins https://github.com/dvb6666/esphome-components/blob/main/examples/test-gpio-viewer.yaml

**Comment by wacsy** [comment]
The example from dvb6666 doesn't work for me. It failed the compilation. but the following is good for compilation and OTA:

```
esphome:
  name: e32s2
  friendly_name: gproviewer
  libraries:
    - thelastoutpostworkshop/GPIOViewer
 external_components:
  - source: github://dvb6666/esphome-components
    refresh: 1sec
gpio_viewer:
  port: 82 # default 8080
  sampling_interval: 200 # default 100
web_server:
  port: 80
  version: 3
  local: true
```
Then I can visit it at port 82, but it doesn't give any meaningful information so far.

GPIOViewer is working great with Tasmota on the other hand

**Comment by chrisjanbothma79** [comment]
INFO ESPHome 2025.10.3
INFO Reading configuration g:\esphome\new1.yaml...
INFO Updating https://github.com/dvb6666/esphome-components.git@None
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Scripts\esphome.exe\__main__.py", line 6, in <module>
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 1387, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 1374, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 698, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 442, in write_cpp
    generate_cpp_contents(config)
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 454, in generate_cpp_contents
    CORE.flush_tasks()
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\core\__init__.py", line 779, in flush_tasks
    self.event_loop.flush_tasks()
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\coroutine.py", line 341, in flush_tasks
    next(task.iterator)
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\__main__.py", line 431, in wrapped
    await coro(conf)
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\core\config.py", line 482, in to_code
    cg.add_library(None, None, lib)
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\cpp_generator.py", line 591, in add_library
    CORE.add_library(Library(name, version, repository))
  File "C:\Users\Joamon\AppData\Local\Programs\Python\Python311\Lib\site-packages\esphome\core\__init__.py", line 824, in add_library
    raise ValueError(f"The library for {library.repository} must have a name")
ValueError: The library for https://github.com/dvarrel/AsyncTCP.git must have a name
sys:1: RuntimeWarning: coroutine 'to_code' was never awaited
sys:1: RuntimeWarning: coroutine '_add_platform_defines' was never awaited
sys:1: RuntimeWarning: coroutine '_add_automations' was never awaited
